# Generated by Django 5.0.4 on 2024-04-15 08:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_alter_category_id_alter_dress_id_alter_login_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkinProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=100)),
                ('photo', models.CharField(max_length=500)),
                ('description', models.CharField(max_length=100)),
                ('skintone', models.CharField(max_length=100)),
                ('productType', models.CharField(default='', max_length=500)),
                ('gender', models.CharField(default='', max_length=100)),
                ('occasions', models.CharField(default='', max_length=100)),
                ('CATEGORY', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.category')),
            ],
        ),
    ]
