# Generated by Django 5.0.4 on 2024-04-15 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_skinproducts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dress',
            name='CATEGORY',
        ),
        migrations.RemoveField(
            model_name='user',
            name='LOGIN',
        ),
        migrations.RemoveField(
            model_name='mydress',
            name='USER',
        ),
        migrations.RemoveField(
            model_name='suggestion',
            name='USER',
        ),
        migrations.DeleteModel(
            name='SkinProducts',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Dress',
        ),
        migrations.DeleteModel(
            name='Login',
        ),
        migrations.DeleteModel(
            name='Mydress',
        ),
        migrations.DeleteModel(
            name='Suggestion',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
