# Generated by Django 5.0.4 on 2024-04-15 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skinproducts',
            old_name='productType',
            new_name='skinType',
        ),
    ]
